networks:
  app:

services:
  nginx: 
    image: nginx:latest
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 80:80
    depends_on:
      - statista-api
    networks:
      - app

  statista-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    container_name: statista_web_api
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: statista
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql_container
    networks:
      - app

volumes:
  db_data:
